---

- name: Install tools
  package:
    name: vim
    state: present

- name: Configure bash aliases
  copy:
    dest: '/home/{{ ansible_user }}/.bash_aliases'
    content: |
      alias ll='ls -alF'
    owner: '{{ ansible_user }}'

- name: Disable vim auto visual mode on mouse select
  copy:
    dest: '/home/{{ ansible_user }}/.vimrc'
    content: |
      set mouse-=a
    owner: '{{ ansible_user }}' 

- name: Configure timezone
  timezone:
    name: '{{ basic_linux_config_timezone }}'

- name: Add ssh authorized key
  authorized_key:
    user: '{{ ansible_user }}'
    state: present
    key: '{{ basic_linux_config_authorized_key }}'
