---

- name: Start services
  k8s:
    definition: "{{ lookup('file', '{{ ruuvi_k8_definitions_dir }}/{{ item }}') }}"
    state: present
    namespace: default
  loop:
    - influxdb-statefulset.yml
    - influxdb-service.yml
    - grafana-conf-datasources.yml
    - grafana-conf-dashboards.yml
    - grafana-deployment.yml
    - grafana-service.yml
    - ruuvi-deployment.yml
