---

- name: Create dir for dockerfile
  file: 
    path: '{{ ruuvi_dockerfile_dir }}'
    state: directory

- name: Copy ruuvi docker files
  synchronize: 
    src: '{{ ruuvi_dockerfile_src_dir }}/'
    dest: '{{ ruuvi_dockerfile_dir }}'

- name: Build ruuvi docker image
  docker_image:
    path: '{{ ruuvi_dockerfile_dir }}'
    name: ruuvi
    force: '{{ ruuvi_force_image_build | default(false) }}'

- name: Start services
  k8s:
    definition: "{{ lookup('file', '{{ ruuvi_k8_definitions_dir }}/{{ item }}') }}"
    state: present
    namespace: default
  loop:
    - influxdb-statefulset.yml
    - influxdb-service.yml
    - grafana-conf-datasources.yml
    - grafana-conf-dashboards.yml
    - grafana-deployment.yml
    - grafana-service.yml
    - ruuvi-deployment.yml
