---

kubernetes_local_persistent_volumes_map:
  - name: local-pv-large
    labels:
      pv-type: sd-card
    capacity: 5Gi
    path: /var/lib/kubernetes/pv/large
  - name: local-pv-small
    labels:
      pv-type: sd-card
    capacity: 1Gi
    path: /var/lib/kubernetes/pv/small
