---

basic_linux_config_timezone: Set to your timezone (e.g Europe/Helsinki)
basic_linux_config_authorized_key: "{{ lookup('file', 'path to public key') }}"

ansible_ssh_private_key_file: path to private key
