---

- hosts: all
  roles:
    - role: basic-linux-config
      tags: role-basic-linux-config

    - role: dev-sec.ssh-hardening
      tags: role-ssh-hardening

- hosts: kubernetes-all-nodes
  roles: 
    - role: docker
      tags: role-docker
    
    - role: kubeadm
      tags: role-kubeadm

    - role: bluetooth
      tags: role-bluetooth

- hosts: kubernetes-master-nodes
  roles:
    - role: kubernetes-master
      tags: role-kubernetes-master
        
- hosts: kubernetes-worker-nodes
  roles:
    - role: kubernetes-worker
      tags: role-kubernetes-worker

- hosts: kubernetes-master-nodes
  run_once: true
  become: false
  vars:
    ruuvi_dockerfile_src_dir: '{{ playbook_dir }}/../ruuvi'
    ruuvi_k8_definitions_dir: '{{ playbook_dir }}/../ruuvi-definitions'
  roles:
    - role: ruuvi
      tags: role-ruuvi
