---

- name: Add GCloud key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add Kubernetes repository
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present

- name: Install kubeadm
  package:
    name: kubeadm
    state: present

- name: Check swap state
  command: swapon --summary
  register: swap_result
  failed_when: false
  changed_when: false
  check_mode: false

- name: Disable swap
  command: '{{ item }}'
  with_items:
    - dphys-swapfile swapoff
    - dphys-swapfile uninstall
    - update-rc.d dphys-swapfile remove
  when: swap_result.stdout != ''

- name: Prevent swap on boot
  service:
    name: dphys-swapfile
    state: stopped
    enabled: false

- name: Configure iptables bridge
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: '1'
    state: present

- name: Install openshift library for managing kubernetes with Ansible
  pip:
    name: openshift
